file1 = open('output.txt','w')
write_file = file1.write('hello, python!')
file1.close()
file1 = open('output.txt','a')
appending_file = file1.write('learning file handling in python')
file1.close()
file1 =open('output.txt','r')
reading_file = file1.read()
print(reading_file)
file1.close()
